---
_meta:
  type: "rolesmapping"
  config_version: 2

byk-analyst:
  reserved: false
  hidden: false
  backend_roles:
    - "ROLE_ANALYST"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]
manage_snapshots:
  reserved: true
  hidden: false
  backend_roles:
    - "snapshotrestore"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]
own_index:
  reserved: false
  hidden: false
  backend_roles: [ ]
  hosts: [ ]
  users:
    - "*"
  and_backend_roles: [ ]
  description: "Allow full access to an index named like the username"
kibana_user:
  reserved: false
  hidden: false
  backend_roles:
    - "kibanauser"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]
  description: "Maps kibanauser to kibana_user"
all_access:
  reserved: true
  hidden: false
  backend_roles:
    - "admin"
    - "ROLE_ADMINSTRATOR"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]
  description: "Maps ROLE_ADMINSTRATOR to all_access"
readall:
  reserved: true
  hidden: false
  backend_roles:
    - "readall"
    - "ROLE_SERVICE_MANAGER"
    - "ROLE_ANALYST"
    - "ROLE_CHATBOT_TRAINER"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]
kibana_server:
  reserved: true
  hidden: false
  backend_roles: [ ]
  hosts: [ ]
  users:
    - "kibanaserver"
  and_backend_roles: [ ]
