version: '3.9'

services:
  byk-public-ruuter:
    container_name: byk-public-ruuter
    image: riaee/byk-chatbot-public-ruuter:v0.2.84
    environment:
      - ruuter.cookie.sameSitePolicy=None
      - legacy-portal-integration.sessionCookieDomain=buerokratt.ee
      - logging.level.root=INFO
    volumes:
      - ./ruuter/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./ruuter/public.urls.docker.json:/usr/local/tomcat/urls.env.json:ro
      - ./ruuter/cert.crt:/usr/local/tomcat/conf/cert.crt:ro
      - ./ruuter/key.key:/usr/local/tomcat/conf/key.key:ro
      - ./location/of/training-prv-key:/root/.ssh/training-prv-key:ro
    ports:
      - 8080:8443
    restart: always
    networks:
      - bykstack
  byk-private-ruuter:
    container_name: byk-private-ruuter
    image: riaee/byk-chatbot-private-ruuter:v0.2.1
    environment:
      - legacy-portal-integration.sessionCookieDomain=buerokratt.ee
      - logging.level.root=INFO
    volumes:
      - ./ruuter/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./ruuter/private.urls.docker.json:/usr/local/tomcat/urls.env.json:ro
      - ./ruuter/cert.crt:/usr/local/tomcat/conf/cert.crt:ro
      - ./ruuter/key.key:/usr/local/tomcat/conf/key.key:ro
    ports:
      - 8443:8443
    restart: always
    networks:
      - bykstack
  byk-dmapper:
    container_name: byk-dmapper
    image: riaee/byk-dmapper:v0.2.9
    environment:
      - logging.level.root=INFO
    ports:
      - 8081:8443
    volumes:
      - ./dmapper/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./dmapper/cert.crt:/usr/local/tomcat/conf/tls.crt:ro
      - ./dmapper/key.key:/usr/local/tomcat/conf/tls.key:ro
    restart: always
    networks:
      - bykstack
  byk-widget:
    container_name: byk-widget
    image: riaee/byk-chat-widget:v0.2.1
    ports:
      - 3000:443
    volumes:
      - ./chat-widget/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./chat-widget/index.html:/usr/share/nginx/html/widget/index.html:ro
      - ./chat-widget/cert.crt:/etc/tls/tls.crt:ro
      - ./chat-widget/key.key:/etc/tls/tls.key:ro
    restart: always
    networks:
      - bykstack
  byk-customer-service:
    container_name: byk-customer-service
    image: riaee/byk-customer-service:v0.2.3
    ports:
      - 3001:443
    volumes:
      - ./customer-support/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./customer-support/env-config.js:/usr/share/nginx/html/customer-service/env-config.js:ro
      - ./customer-support/cert.crt:/etc/ssl/certs/cert.crt:ro
      - ./customer-support/key.key:/etc/ssl/certs/key.key:ro
    restart: always
    networks:
      - bykstack
  byk-tim:
    container_name: byk-tim
    image: riaee/byk-tim:v0.2.4
    environment:
      - security.allowlist.jwt=byk-public-ruuter,byk-private-ruuter,byk-dmapper,byk-widget,byk-customer-service,byk-resql
      - spring.datasource.url=jdbc:postgresql://tim-postgresql:5432/tim
      - spring.datasource.username=tim
      - spring.datasource.password=safe_tim_password
      - security.oauth2.client.client-id=tara_client_id
      - security.oauth2.client.client-secret=tara_client_secret
      - security.oauth2.client.registered-redirect-uri=https://tim.byk.buerokratt.ee/authenticate
      - security.oauth2.client.user-authorization-uri=https://tara.ria.ee/oidc/authorize
      - security.oauth2.client.access-token-uri=https://tara.ria.ee/oidc/token
      - security.oauth2.resource.jwk.key-set-uri=https://tara.ria.ee/oidc/jwks
      - auth.success.redirect.whitelist=https://admin.byk.buerokratt.ee/auth/callback,https://byk.buerokratt.ee,https://byk.buerokratt.ee/auth/callback,https://admin.byk.buerokratt.ee
      - frontpage.redirect.url=https://admin.byk.buerokratt.ee
      - "headers.contentSecurityPolicy=upgrade-insecure-requests; default-src 'self' 'unsafe-inline' 'unsafe-eval' https://tim.byk.buerokratt.ee https://admin.byk.buerokratt.ee https://ruuter.byk.buerokratt.ee https://priv-ruuter.byk.buerokratt.ee byk-tim byk-public-ruuter byk-private-ruuter byk-customer-service; object-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://byk.buerokratt.ee https://admin.byk.buerokratt.ee https://tim.byk.buerokratt.ee; connect-src 'self' https://byk.buerokratt.ee https://tim.byk.buerokratt.eehttps://admin.byk.buerokratt.ee https://ruuter.byk.buerokratt.ee https://priv-ruuter.byk.buerokratt.ee; frame-src 'self'; media-src 'none'"
      - legacy-portal-integration.legacyUrl=arendus.eesti.ee
      - legacy-portal-integration.legacyPortalRefererMarker=https://arendus.eesti.ee/portaal
      - cors.allowedOrigins=https://byk.buerokratt.ee,https://admin.byk.buerokratt.ee,https://ruuter.byk.buerokratt.ee,https://priv-ruuter.buerokratt.ee
      - jwt-integration.signature.issuer=byk.buerokratt.ee
      - jwt-integration.signature.key-store-password=safe_keystore_password
      - jwt-integration.signature.key-store=file:/usr/local/tomcat/jwtkeystore.jks
      - spring.profiles.active=dev
      - legacy-portal-integration.sessionCookieDomain=buerokratt.ee
      - logging.level.root=INFO
    ports:
      - 8085:8443
    volumes:
      - ./tim/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./tim/jwtkeystore.jks:/usr/local/tomcat/jwtkeystore.jks:ro
      - ./tim/cert.crt:/usr/local/tomcat/conf/cert.crt:ro
      - ./tim/key.key:/usr/local/tomcat/conf/key.key:ro
    restart: always
    networks:
      - bykstack
  byk-resql:
    container_name: byk-resql
    image: riaee/byk-resql:v0.3.6
    environment:
      - sqlms.datasources.[0].name=byk
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://users-db:5433/byk?sslmode=require
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=safe_byk_password
      - logging.level.org.springframework.boot=INFO
    ports:
      - 8082:8443
    volumes:
      - ./resql/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./resql/cert.crt:/usr/local/tomcat/conf/cert.crt:ro
      - ./resql/key.key:/usr/local/tomcat/conf/key.key:ro
    restart: always
    networks:
      - bykstack
  byk-chatbot-opensearch-node1:
    image: opensearchproject/opensearch:1.2.4
    container_name: chatbot-opensearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch/jvm.options:/usr/share/opensearch/config/jvm.options:ro
      - ./opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
      - ./config/root-ca.pem:/usr/share/opensearch/config/root-ca.pem:ro
      - ./config/admin.pem:/usr/share/opensearch/config/admin.pem:ro
      - ./config/admin-key.pem:/usr/share/opensearch/config/admin-key.pem:ro
      - ./config/node1.pem:/usr/share/opensearch/config/node1.pem:ro
      - ./config/node1-key.pem:/usr/share/opensearch/config/node1-key.pem:ro
      - ./securityconfig/config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml:ro
      - ./securityconfig/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml:ro
      - ./securityconfig/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml:ro
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer
    restart: always
    networks:
      - bykstack

  byk-chatbot-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: chatbot-dashboards
    volumes:
      - ./opensearch-dashboards/dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro
      - ./config/root-ca.pem:/usr/share/opensearch-dashboards/config/root-ca.pem:ro
      - ./config/tls.crt:/usr/share/opensearch-dashboards/config/tls.crt:ro
      - ./config/tls.key:/usr/share/opensearch-dashboards/config/tls.key:ro
      - ./assets:/usr/share/opensearch-dashboards/assets:ro
    ports:
      - "5601:5601"
    expose:
      - "5601"
    restart: always
    networks:
      - bykstack

  byk-logstash:
    image: riaee/byk:chatbot-logstash-20220616
    container_name: chatbot-logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf:ro
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    command: bash -c "logstash -f /usr/share/logstash/config/logstash.conf"
    ports:
      - "8087:8443"
    depends_on:
      - byk-chatbot-opensearch-node1
    restart: always
    networks:
      - bykstack

volumes:
  opensearch-data:
    driver: local
networks:
  bykstack:
    name: bykstack
    driver: bridge
