version: '3.9'
services:
  byk-users-liquibase:
    build:
      context: .
    environment:
      - db_url=users-db:5432/byk
      - db_user=byk
      - db_user_pswd=bykpass
    ports:
      - 8000:8000
    restart: always
    networks:
      - bykstack

networks:
  bykstack:
    name: bykstack
